on: push
name: Check repo organization
jobs:
  check-repo-organization:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gchism94/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(
          c("_extra/*", "images/*", "_freeze/*",
            "data/*.csv", "data/*.csv", "data/*.xls", "data/*.xlsx", "data/*.RDS", "data/README.md", "data/*.qmd",
            "utils/*.py", "utils/README.md",
            "README.md", "project-final.Rproj",
            "index.qmd", "presentation.qmd", "proposal.qmd", "about.qmd", "_quarto.yml", "data/*.scss", "*.ipynb", "requirements.txt", "FinalPresentationLink.txt", "FinalProject Write-Up-Team5.pdf", "Team 5 Presentation.pdf"
            )
            )          
        })
      shell: Rscript {0}
